### ISSUE TITLE
make configuration in composition root automatic. and update the project to dotnet 8 

### ISSUE THREAD

**Issue by ehsanhrz** [thisisnabi/Installer.Microsoft.ServiceCollection#2]
hey Nabi, I was using similar approach for registering my features installer like
`public static class UsersInstaller 
{
    public static void Register(IServiceCollection serviceCollection)
    {
        serviceCollection.AddScoped<GetUser>();
        serviceCollection.AddScoped<UserCud>();
    }
}`
and in my setup I'm calling the installer like this 
`
       SharedInstaller.Register(builder.Services);
        RolesInstaller.Register(builder.Services);
        UsersInstaller.Register(builder.Services);
        AuthenticationInstaller.Register(builder.Services);
`
but as you can see its not good approach and after seeing your project I decided to use it but its on dotnet 7 so lets update it.
and I think it will be better to create a extension method that scans the assembly and registers it automatically something like
`
builder.Services.InstallModules()
`
if we could delete these 
`
using assemblyApplication = Installer.ConsumerWebAppl.IAssemblyMaker;
using assemblyInfrastructure = Installer.ConsumerWebApp.Infrastructure.IAssemblyMaker;
` It will be awesome 
I can try to implement these features if you like

**Comment by thisisnabi** [comment]
Hey ehsan, 

Is this signature work like a scanner?
`builder.Services.InstallModules()`

If yes, let's to start and make your PR.

**Comment by ehsanhrz** [comment]
Yes it will work like a scanner, after getting the list of the types which inherited the installer interface with help of Activator class I will create an instance for each installer . After that each instance will run his register function and will be disposed of by GC . It looks like Scruter library with a better and simple approach.
